import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${poppins.className} dark:bg-white text-[#151515]`}>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
