import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import { ToastContainer } from 'react-toastify';
import NextAuthSessionProviders from "@/Providers/NextAuthSessionProviders";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "CAR DOCTOR | HOME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <ToastContainer />
      <NextAuthSessionProviders>
        <body className={`${poppins.className} dark:bg-white text-[#151515]`}>
          <Navbar />
          <main>
            {children}
          </main>
        </body>
      </NextAuthSessionProviders>
    </html>
  );
}
